version: "3.8"

x-base-settings: &base_service_settings
  tty: true
  user: node
  env_file: .env
  network_mode: "host"
  build: &base_build_settings
    context: .
  environment: &base_environment_settings
    # Colorize the terminal in the container if possible
    TERM: "${TERM:-}"
    NVIDIA_DRIVER_CAPABILITIES: all
  deploy:
    resources:
      reservations:
        devices:
          - capabilities:
            - gpu


services:

  base:
    <<: *base_service_settings
    image: rapidsai/node:${RAPIDS_VERSION:-latest}-devel-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-base-${ARCH:-amd64}
    build:
      <<: *base_build_settings
      dockerfile: dockerfiles/devel/01-base.Dockerfile
      args:
        UID: ${UID:-1000}
        NODE_VERSION: ${NODE_VERSION:-15.14.0}
        ADDITIONAL_GROUPS: "${ARCH_USER_GROUPS:---groups sudo}"
        FROM_IMAGE: ${ARCH_BASE_IMAGE:-}
        FROM_IMAGE_DEFAULT: nvidia/cudagl:${CUDA_VERSION:-11.2.2}-devel-${LINUX_VERSION:-ubuntu20.04}

  main:
    <<: *base_service_settings
    image: rapidsai/node:${RAPIDS_VERSION:-latest}-devel-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-main-${ARCH:-amd64}
    build:
      <<: *base_build_settings
      dockerfile: dockerfiles/devel/02-main.Dockerfile
      args:
        FROM_IMAGE: rapidsai/node:${RAPIDS_VERSION:-latest}-devel-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-base-${ARCH:-amd64}
        # FROM_IMAGE: rapidsai/node:${RAPIDS_VERSION:-latest}-devel-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-nvstream-${ARCH:-amd64}

  nvstream:
    <<: *base_service_settings
    image: rapidsai/node:${RAPIDS_VERSION:-latest}-devel-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-nvstream-${ARCH:-amd64}
    build:
      <<: *base_build_settings
      context: internal
      dockerfile: ../dockerfiles/devel/03-nvstream.Dockerfile
      args:
        CUDA_10_2_IMAGE: ${ARCH_BASE_IMAGE:-nvidia/cuda:10.2-devel-ubuntu18.04}
        # FROM_IMAGE: rapidsai/node:${RAPIDS_VERSION:-latest}-devel-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-base-${ARCH:-amd64}
        FROM_IMAGE: rapidsai/node:${RAPIDS_VERSION:-latest}-devel-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-main-${ARCH:-amd64}
    volumes:
      - &workdir "${PWD}:/opt/node-rapids:rw"
      - &etc_fonts "/etc/fonts:/etc/fonts:ro"
      - &x11_socket "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - &usr_share_fonts "/usr/share/fonts:/usr/share/fonts:ro"
      - &usr_share_icons "/usr/share/icons:/usr/share/icons:ro"
      - &etc_timezone "/etc/timezone:/etc/timezone"
      - &etc_localtime "/etc/localtime:/etc/localtime"
      - &dbus_system_bus_socket "/run/dbus/system_bus_socket:/run/dbus/system_bus_socket"
      - &xdg_runtime_dir "${XDG_RUNTIME_DIR:-/run/user/$UID}:${XDG_RUNTIME_DIR:-/run/user/$UID}"
    working_dir: /opt/node-rapids
    environment:
      <<: *base_environment_settings
      # Use the host's X11 display
      DISPLAY: "${DISPLAY:-}"
      XAUTHORITY: "${XAUTHORITY:-}"
      XDG_SESSION_TYPE: "${XDG_SESSION_TYPE:-}"
      XDG_RUNTIME_DIR: "${XDG_RUNTIME_DIR:-/run/user/$UID}"
      DBUS_SESSION_BUS_ADDRESS: "${DBUS_SESSION_BUS_ADDRESS:-unix:path=/run/user/$UID/bus}"
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined

  nteract:
    <<: *base_service_settings
    image: rapidsai/node:${RAPIDS_VERSION:-latest}-devel-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-nteract-${ARCH:-amd64}
    build:
      <<: *base_build_settings
      dockerfile: dockerfiles/devel/04-nteract.Dockerfile
      args:
        # FROM_IMAGE: rapidsai/node:${RAPIDS_VERSION:-latest}-devel-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-main-${ARCH:-amd64}
        FROM_IMAGE: rapidsai/node:${RAPIDS_VERSION:-latest}-devel-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-nvstream-${ARCH:-amd64}
    environment:
      <<: *base_environment_settings
      # Use the host's X11 display
      DISPLAY: "${DISPLAY:-}"
      XAUTHORITY: "${XAUTHORITY:-}"
      XDG_SESSION_TYPE: "${XDG_SESSION_TYPE:-}"
      XDG_RUNTIME_DIR: "${XDG_RUNTIME_DIR:-/run/user/$UID}"
      DBUS_SESSION_BUS_ADDRESS: "${DBUS_SESSION_BUS_ADDRESS:-unix:path=/run/user/$UID/bus}"
      QT_AUTO_SCREEN_SCALE_FACTOR: 0
    volumes:
      - *workdir
      - *etc_fonts
      - *x11_socket
      - *usr_share_fonts
      - *usr_share_icons
      - *etc_timezone
      - *etc_localtime
      - *dbus_system_bus_socket
      - *xdg_runtime_dir
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined
    command: nteract
