version: "3.8"

x-base-settings: &base_service_settings
  tty: true
  user: node
  env_file: .env
  build: &base_build_settings
    context: .
  environment: &base_environment_settings
    # Colorize the terminal in the container if possible
    TERM: "${TERM:-}"
  deploy:
    resources:
      reservations:
        devices:
          - capabilities:
            - gpu

x-main-service-settings: &main_service_settings
  <<: *base_service_settings
  network_mode: "host"
  build: &main_build_settings
    <<: *base_build_settings
    args: &main_build_args
      ARCH: "${ARCH:-amd64}"
      CUDA_VERSION: "${CUDA_VERSION-11.2.2}"
      LINUX_VERSION: "${LINUX_VERSION-ubuntu20.04}"
      FROM_IMAGE: rapidsai/node:${RAPIDS_VERSION:-latest}-runtime-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-nvstream-${ARCH:-amd64}
      DEVEL_IMAGE: rapidsai/node:${RAPIDS_VERSION:-latest}-devel-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-build-${ARCH:-amd64}
  environment: &main_environment_variables
    <<: *base_environment_settings
    # Use the host's X11 display
    DISPLAY: "${DISPLAY:-}"
    XAUTHORITY: "${XAUTHORITY:-}"
    XDG_SESSION_TYPE: "${XDG_SESSION_TYPE:-}"

services:

  base:
    <<: *base_service_settings
    image: rapidsai/node:${RAPIDS_VERSION:-latest}-runtime-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-base-${ARCH:-amd64}
    build:
      <<: *base_build_settings
      dockerfile: dockerfiles/runtime/01-base.Dockerfile
      args:
        UID: ${UID:-1000}
        ADDITIONAL_GROUPS: ${ARCH_USER_GROUPS:-}
        FROM_IMAGE: ${ARCH_BASE_IMAGE:-}
        FROM_IMAGE_DEFAULT: nvidia/cudagl:${CUDA_VERSION:-11.2.2}-runtime-${LINUX_VERSION:-ubuntu20.04}
        DEVEL_IMAGE: rapidsai/node:${RAPIDS_VERSION:-latest}-devel-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-base-${ARCH:-amd64}

  nvstream:
    <<: *base_service_settings
    image: rapidsai/node:${RAPIDS_VERSION:-latest}-runtime-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-nvstream-${ARCH:-amd64}
    build:
      <<: *base_build_settings
      dockerfile: dockerfiles/runtime/02-nvstream.Dockerfile
      args:
        FROM_IMAGE: rapidsai/node:${RAPIDS_VERSION:-latest}-runtime-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-base-${ARCH:-amd64}
        DEVEL_IMAGE: rapidsai/node:${RAPIDS_VERSION:-latest}-devel-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-main-${ARCH:-amd64}

  build:
    <<: *base_service_settings
    image: rapidsai/node:${RAPIDS_VERSION:-latest}-devel-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-build-${ARCH:-amd64}
    build:
      <<: *base_build_settings
      dockerfile: dockerfiles/runtime/03-build.Dockerfile
      args:
        DISPLAY: "${DISPLAY:-}"
        PARALLEL_LEVEL: "${PARALLEL_LEVEL:-}"
        RAPIDS_VERSION: "${RAPIDS_VERSION:-}"
        SCCACHE_REGION: "${SCCACHE_REGION:-}"
        SCCACHE_BUCKET: "${SCCACHE_BUCKET:-}"
        SCCACHE_CACHE_SIZE: "${SCCACHE_CACHE_SIZE:-}"
        SCCACHE_IDLE_TIMEOUT: "${SCCACHE_IDLE_TIMEOUT:-}"
        AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:-}"
        AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:-}"
        FROM_IMAGE: rapidsai/node:${RAPIDS_VERSION:-latest}-devel-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-main-${ARCH:-amd64}

  main:
    <<: *main_service_settings
    image: rapidsai/node:${RAPIDS_VERSION:-latest}-runtime-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-${ARCH:-amd64}-main
    build:
      <<: *main_build_settings
      dockerfile: dockerfiles/runtime/main.Dockerfile

  demo:
    <<: *main_service_settings
    image: rapidsai/node:${RAPIDS_VERSION:-latest}-runtime-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-${ARCH:-amd64}-demo-main
    build:
      <<: *main_build_settings
      dockerfile: dockerfiles/runtime/demo.Dockerfile

  glfw:
    <<: *main_service_settings
    image: rapidsai/node:${RAPIDS_VERSION:-latest}-runtime-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-${ARCH:-amd64}-glfw-main
    build:
      <<: *main_build_settings
      dockerfile: dockerfiles/runtime/glfw.Dockerfile

  cudf:
    <<: *main_service_settings
    image: rapidsai/node:${RAPIDS_VERSION:-latest}-runtime-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-${ARCH:-amd64}-cudf-main
    build:
      <<: *main_build_settings
      dockerfile: dockerfiles/runtime/cudf.Dockerfile

  blazingsql:
    <<: *main_service_settings
    image: rapidsai/node:${RAPIDS_VERSION:-latest}-runtime-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-${ARCH:-amd64}-blazingsql-main
    build:
      <<: *main_build_settings
      dockerfile: dockerfiles/runtime/blazingsql.Dockerfile

  cuml:
    <<: *main_service_settings
    image: rapidsai/node:${RAPIDS_VERSION:-latest}-runtime-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-${ARCH:-amd64}-cuml-main
    build:
      <<: *main_build_settings
      dockerfile: dockerfiles/runtime/cuml.Dockerfile

  cugraph:
    <<: *main_service_settings
    image: rapidsai/node:${RAPIDS_VERSION:-latest}-runtime-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-${ARCH:-amd64}-cugraph-main
    build:
      <<: *main_build_settings
      dockerfile: dockerfiles/runtime/cugraph.Dockerfile

  cuspatial:
    <<: *main_service_settings
    image: rapidsai/node:${RAPIDS_VERSION:-latest}-runtime-node${NODE_VERSION:-15.14.0}-cuda${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-${ARCH:-amd64}-cuspatial-main
    build:
      <<: *main_build_settings
      dockerfile: dockerfiles/runtime/cuspatial.Dockerfile
